### ISSUE TITLE
Dependency conflict in dev-requirements.txt

### ISSUE THREAD

**Issue by barneydobson** [ImperialCollegeLondon/pip-tools-template#107]
Following the Usage instructions in the readme.txt.

For this command:
`pip install -r dev-requirements.txt`

I get the following error
```
ERROR: Cannot install -r dev-requirements.txt (line 67) and platformdirs==4.1.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested platformdirs==4.1.0
    virtualenv 20.24.5 depends on platformdirs<4 and >=3.9.1

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

Seemed to be resolved by changing:
`platformdirs<=4.1.0` in `dev-requirements.txt`

Also would it be sensible to add `git` to the `dev-requirements.txt`

**Comment by dalonsoa** [comment]
`git` is not a python dependency, so it cannot be added to the requirements of the project.

I'll look into the other issue.

**Comment by AdrianDAlessandro** [comment]
This is because of an issue with the dependabot automatic updates only updating one package at a time and not testing for compatibility with the rest of the packages. One way to prevent this in future would be to require that tests pass before running the auto-merge job in `auto-merge.yml`
